#!/usr/bin/env bash
SCRIPTPATH="$(dirname $(readlink -f ${BASH_SOURCE[0]}))"
# shellcheck source=./lib/core.sh
source "$SCRIPTPATH/core.sh"

# Detect Sway
if ! [ -z "$SWAYSOCK" ]; then
    XDG_CURRENT_DESKTOP=sway
fi

# Use lowercase value of envvar
case "${XDG_CURRENT_DESKTOP,,}" in
    hyprland)
        WMLIB="${SCRIPTPATH}/wm/hyprland.sh"
        ;;
    niri)
        WMLIB="${SCRIPTPATH}/wm/niri.sh"
        ;;
    sway)
        WMLIB="${SCRIPTPATH}/wm/sway.sh"
        ;;
    *)
        WMLIB="/dev/null"
        ;;
esac

# shellcheck source=/dev/null
source "$WMLIB"
export ALL=(
    $(cat $SCRIPTPATH/core.sh | grep ^function | cut -f2 -d' ' | tr -d '()')
    $(cat $WMLIB | grep ^function | cut -f2 -d' ' | tr -d '()')
)

# Exec function directly if provided arguments
if [[ "$#" -gt 0 ]] && [[ " ${ALL[*]} " =~ " $1 " ]]; then
    # Directly call the first argument, with remaining arguments passed in
    "$1" "${@:2}"
else
    >&2 echo "Valid functions:"
    for func in "${ALL[@]}"; do
        >&2 echo " - $func"
    done
fi
